import json

menu_data = {
    "categories": [
        {"id": "week", "name": "Menu of the Week", "name_vi": "Cocktail Tuần Này", "icon": "🍸", "station": "bar"},
        {"id": "cocktail", "name": "Cocktails", "name_vi": "Cocktail Đặc Biệt & Classic", "icon": "🍹", "station": "bar"},
        {"id": "mocktail", "name": "Mocktails", "name_vi": "Mocktail (Không Cồn)", "icon": "🧃", "station": "bar"},
        {"id": "bites", "name": "Bites & Snacks", "name_vi": "Món Nhắm / Bếp", "icon": "🍟", "station": "kitchen"},
        {"id": "beer", "name": "Craft Beer & Cider", "name_vi": "Bia Thủ Công & Tepache", "icon": "🍺", "station": "bar"},
        {"id": "wine_shot", "name": "Wine & Shots", "name_vi": "Rượu Vang & Rượu Shot", "icon": "🍷", "station": "bar"}
    ],
    "items": [
        # --- MENU OF THE WEEK ---
        {
            "id": "w01",
            "name": "SCARLET BLOOM",
            "name_vi": "Scarlet Bloom",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Sự kết hợp cuốn hút giữa Tequila và Campari đắng nhẹ, cân bằng bởi vị vải ngọt thanh cùng hương hoa dịu nhẹ.",
            "description_en": "A striking balance of vibrant tequila and bittersweet Campari, softened by sweet lychee notes for a rich, floral finish.",
            "ingredients": ["Tequila", "Lychee Cordial", "Campari", "Choco Bitter", "Sour Water"],
            "badge": "Signature",
            "is_available": True
        },
        {
            "id": "w02",
            "name": "ASTRAL STAR",
            "name_vi": "Astral Star",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Vị Gin thảo mộc tươi mát kết hợp độc đáo cùng cordial khế và limecello chua thanh, mang lại cảm giác sảng khoái trọn vẹn.",
            "description_en": "A crisp, botanical fusion of classic gin and refreshing starfruit, brightened with zesty limecello for an uplifting sip.",
            "ingredients": ["Gin", "Home-made Limecello", "Starfruit Cordial", "Juniper Liqueur"],
            "badge": "Refreshing",
            "is_available": True
        },
        {
            "id": "w03",
            "name": "HOP & PEAR",
            "name_vi": "Hop & Pear",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Phong cách thanh nhẹ, bừng sáng vị lê ngọt dịu quyện cùng whisky và sủi bọt soda đã miệng.",
            "description_en": "A light, effervescent whiskey highball infused with sweet pear cordial and a lively fizzy finish.",
            "ingredients": ["Whisky", "Pear Cordial", "Soda"],
            "badge": "Highball",
            "is_available": True
        },
        {
            "id": "w04",
            "name": "NOCTURNE CACAO",
            "name_vi": "Nocturne Cacao",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Nốt trầm đầm ấm của cà phê đắng nhẹ quyện cùng gin, vị cam tươi và anh đào mọng nước cho buổi đêm sâu lắng.",
            "description_en": "A sophisticated nightcap blending sharp gin, rich coffee, and bright citrus with a touch of sweet cherry.",
            "ingredients": ["Gin", "Coffee Liqueur", "Cherry Cordial", "Orangecello"],
            "badge": "Nightcap",
            "is_available": True
        },
        {
            "id": "w05",
            "name": "COLD DRIFT",
            "name_vi": "Cold Drift",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Chất Rum nền mượt mà hòa cùng vị táo xanh giòn ngọt và lemoncello chua mát, cực kỳ dễ uống.",
            "description_en": "A refreshing, citrus-forward rum mix driven by crisp green apple and bright lemoncello.",
            "ingredients": ["Rum", "Apple Cordial", "Home-made Lemoncello"],
            "badge": "Easy Sip",
            "is_available": True
        },
        {
            "id": "w06",
            "name": "HEATWAVE GOLD",
            "name_vi": "Heatwave Gold",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Vị xoài nhiệt đới chín mọng trên nền whisky đằm đặm, nhấn nhá chút cay nồng kích thích vị giác.",
            "description_en": "A tropical, vibrant whiskey cocktail featuring juicy mango cordial balanced by a warm, spicy kick.",
            "ingredients": ["Whiskey", "Mango Cordial", "Spicy Bitter"],
            "badge": "Tropical & Spicy",
            "is_available": True
        },
        {
            "id": "w07",
            "name": "VELVET BANANE",
            "name_vi": "Velvet Banane",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Sự biến tấu thú vị giữa whisky, vị chuối béo dịu và cranberry soda chua nhẹ sủi bọt vui tươi.",
            "description_en": "A playful yet refined blend of smooth whisky, rich banana liqueur, and tart cranberry soda.",
            "ingredients": ["Whisky", "Banana Liqueur", "Cranberry Soda"],
            "badge": "Creamy & Tart",
            "is_available": True
        },
        {
            "id": "w08",
            "name": "SILK SONIC",
            "name_vi": "Silk Sonic",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Biến tấu sảng khoái trên nền Gin & Tonic kinh điển, hòa quyện vị lê ngọt dịu cùng lemoncello chua thanh mát lạnh.",
            "description_en": "A crisp, effervescent twist on the classic Gin & Tonic, combining sweet pear cordial with bright, zesty lemoncello.",
            "ingredients": ["Gin", "Pear Cordial", "Lemoncello", "Tonic"],
            "badge": "Crisp G&T",
            "is_available": True
        },
        {
            "id": "w09",
            "name": "ONYX",
            "name_vi": "Onyx",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Nền whisky đậm đà hòa quyện cùng cacao đắng nhẹ, điểm xuyết thảo mộc bạch đậu khấu nhà làm cho hậu vị khói êm đằm.",
            "description_en": "A bold, spirit-forward blend of aged whiskies and dark cacao, deepened with home-made cardamom for a smoky, velvety finish.",
            "ingredients": ["Aged Whisky", "Cacao Liqueur", "Home-made Cardamom Liqueur"],
            "badge": "Spirit-Forward",
            "is_available": True
        },
        {
            "id": "w10",
            "name": "BOTANICAL FLORA",
            "name_vi": "Botanical Flora",
            "category": "week",
            "station": "bar",
            "price": 180000,
            "description_vi": "Gu uống thanh lịch và khô nhẹ, kết hợp gin thảo mộc, vang trắng cùng lemoncello nhà làm thơm ngát.",
            "description_en": "An elegant, dry aperitif pairing aromatic gin with home-made lemoncello and crisp white wine.",
            "ingredients": ["Gin", "White Wine", "Home-made Lemoncello"],
            "badge": "Dry & Elegant",
            "is_available": True
        },

        # --- BITES & SNACKS (KITCHEN) ---
        {
            "id": "b01",
            "name": "FRENCH FRIES WITH GARLIC FISH SAUCE",
            "name_vi": "Khoai tây chiên xốc mắm tỏi",
            "category": "bites",
            "station": "kitchen",
            "price": 70000,
            "description_vi": "Khoai tây chiên vàng giòn xốc nước mắm tỏi thơm lừng, đậm đà bắt vị.",
            "description_en": "Crispy golden french fries tossed in aromatic savory garlic fish sauce glaze.",
            "ingredients": ["Khoai tây tươi chiên", "Tỏi phi", "Sốt mắm rim đường"],
            "badge": "Best Seller",
            "is_available": True
        },
        {
            "id": "b02",
            "name": "FRENCH FRIES WITH BACON & CHEESE",
            "name_vi": "Khoai tây chiên phủ bacon & phô mai",
            "category": "bites",
            "station": "kitchen",
            "price": 95000,
            "description_vi": "Khoai chiên giòn rụm ngập sốt phô mai béo ngậy cùng vụn thịt xông khói thơm phức.",
            "description_en": "Crispy fries loaded with melted cheese sauce and crispy savory bacon bits.",
            "ingredients": ["Khoai tây chiên", "Bacon giòn", "Sốt phô mai tan chảy"],
            "badge": "Rich & Savory",
            "is_available": True
        },
        {
            "id": "b03",
            "name": "FRENCH FRIES WITH CHEESE",
            "name_vi": "Khoai tây chiên phủ phô mai",
            "category": "bites",
            "station": "kitchen",
            "price": 85000,
            "description_vi": "Khoai tây cọng lớn chiên nóng hổi phủ lớp sốt cheddar phô mai béo mịn.",
            "description_en": "Golden fries drizzled with warm, velvety melted cheese.",
            "ingredients": ["Khoai tây chiên", "Sốt phô mai béo"],
            "badge": "",
            "is_available": True
        },
        {
            "id": "b04",
            "name": "FRENCH FRIES CLASSIC",
            "name_vi": "Khoai tây cọng chiên giòn",
            "category": "bites",
            "station": "kitchen",
            "price": 55000,
            "description_vi": "Khoai tây truyền thống chiên ráo dầu, chấm kèm tương ớt hoặc sốt mayonnaise.",
            "description_en": "Classic straight-cut french fries, salted and fried to golden perfection.",
            "ingredients": ["Khoai tây giòn", "Muối tiêu", "Tương ớt / Sốt chấm"],
            "badge": "",
            "is_available": True
        },
        {
            "id": "b05",
            "name": "FRIES WITH CREAMY ONION SAUCE",
            "name_vi": "Khoai tây chiên phủ sốt kem hành",
            "category": "bites",
            "station": "kitchen",
            "price": 85000,
            "description_vi": "Khoai chiên thơm giòn rưới đẫm sốt sour cream & hành tây tươi ngậy mát.",
            "description_en": "Crisp fries paired with a luscious homemade sour cream and onion sauce.",
            "ingredients": ["Khoai tây chiên", "Sốt kem hành chua béo"],
            "badge": "Chef Twist",
            "is_available": True
        },
        {
            "id": "b06",
            "name": "CRISPY FRIED MACARONI & CHEESE",
            "name_vi": "Nui chiên giòn phô mai",
            "category": "bites",
            "station": "kitchen",
            "price": 55000,
            "description_vi": "Nui chiên giòn tan rắc bột phô mai thơm phức, món nhắm nhâm nhi bia rượu cực đỉnh.",
            "description_en": "Crispy crunchy fried macaroni tossed in rich aromatic cheddar cheese powder.",
            "ingredients": ["Nui giòn rụm", "Bột phô mai mặn béo"],
            "badge": "Top Snack",
            "is_available": True
        },
        {
            "id": "b07",
            "name": "FRIED WONTON CHIPS",
            "name_vi": "Lá hoành thánh chiên giòn",
            "category": "bites",
            "station": "kitchen",
            "price": 50000,
            "description_vi": "Vỏ hoành thánh chiên giòn rụm màu hổ phách, chấm sốt cay ngọt nhẹ.",
            "description_en": "Golden crispy wonton crackers served with sweet-chili dipping sauce.",
            "ingredients": ["Lá hoành thánh tươi", "Gia vị thảo mộc"],
            "badge": "Crunchy",
            "is_available": True
        },
        {
            "id": "b08",
            "name": "POPCORN CHICKEN + CHEESE (SIZE M)",
            "name_vi": "Gà viên sốt cay phủ phô mai (Size M)",
            "category": "bites",
            "station": "kitchen",
            "price": 95000,
            "description_vi": "Thịt gà viên chiên giòn xốc sốt cay ngọt đậm đà, phủ lớp phô mai tan chảy kéo sợi.",
            "description_en": "Bite-sized crispy popcorn chicken glazed in sweet & spicy sauce, topped with melted cheese.",
            "ingredients": ["Gà viên tươi", "Sốt cay ngọt", "Phô mai Mozzarella tan chảy"],
            "badge": "Popular",
            "is_available": True
        },
        {
            "id": "b09",
            "name": "POPCORN CHICKEN + CHEESE (SIZE L)",
            "name_vi": "Gà viên sốt cay phủ phô mai (Size L)",
            "category": "bites",
            "station": "kitchen",
            "price": 125000,
            "description_vi": "Phần lớn gà viên sốt cay ngọt ngập tràn phô mai thơm lừng cho nhóm bạn.",
            "description_en": "Large portion of spicy sweet popcorn chicken blanketed in molten cheese.",
            "ingredients": ["Gà viên tươi", "Sốt cay ngọt", "Phô mai dẻo kéo sợi"],
            "badge": "For Sharing",
            "is_available": True
        },

        # --- COCKTAILS (BAR) ---
        {
            "id": "c01",
            "name": "TROPICAL VEIL",
            "name_vi": "Tropical Veil",
            "category": "cocktail",
            "station": "bar",
            "price": 170000,
            "description_vi": "Nhiệt đới tươi mát: Rum hòa cùng mứt xoài ngọt lịm và syrup dừa thơm thoang thoảng.",
            "description_en": "Rum meets mango and coconut syrup in a bright tropical twist — warm, fruity, and quietly floral.",
            "ingredients": ["Rum", "Mango Puree", "Cointreau", "Coconut Syrup", "Lime Juice"],
            "badge": "House Pick",
            "is_available": True
        },
        {
            "id": "c02",
            "name": "PINK BLOOM",
            "name_vi": "Pink Bloom",
            "category": "cocktail",
            "station": "bar",
            "price": 170000,
            "description_vi": "Chút đắng, ngọt, thơm, nhẹ nhẹ trôi trôi: Vải và hoa anh đào nhấn nhá chút Campari quyến rũ.",
            "description_en": "Lychee and cherry blossom with a hint of Campari — sweet, floral, and playfully bitter.",
            "ingredients": ["Lychee Puree", "Cherry Blossom Syrup", "Campari", "Gin"],
            "badge": "Floral & Sweet",
            "is_available": True
        },
        {
            "id": "c03",
            "name": "MIDNIGHT CHERRY",
            "name_vi": "Midnight Cherry",
            "category": "cocktail",
            "station": "bar",
            "price": 170000,
            "description_vi": "Cherry và cà phê hòa quyện – đậm, chua nhẹ, lựa chọn hoàn hảo cho những đêm muộn Đà Lạt.",
            "description_en": "Cherry, gin, and coffee liqueur — rich, tangy, and made for slow nights.",
            "ingredients": ["Gin", "Cherry", "Sweet Vermouth", "Coffee Liqueur", "Simple Syrup"],
            "badge": "Dark & Rich",
            "is_available": True
        },
        {
            "id": "c04",
            "name": "GOLDEN PEAR HIGHBALL",
            "name_vi": "Golden Pear Highball",
            "category": "cocktail",
            "station": "bar",
            "price": 170000,
            "description_vi": "Bourbon whisky hoà cùng lê, táo và quế — ngọt dịu, mượt mà và mát lạnh với lớp Orgeat Foam béo mịn.",
            "description_en": "Bourbon whisky with pear, apple & cinnamon purée — gently sweet, smooth, and refreshing topped with Orgeat Foam.",
            "ingredients": ["Bourbon Whisky", "Pear, Apple & Cinnamon Puree", "Orgeat Foam on top"],
            "badge": "Smooth Foam",
            "is_available": True
        },
        {
            "id": "c05",
            "name": "OLD FASHIONED",
            "name_vi": "Old Fashioned",
            "category": "cocktail",
            "station": "bar",
            "price": 190000,
            "description_vi": "Kinh điển vượt thời gian trên nền Bourbon whisky, đường nâu và bitter thảo mộc nồng nàn.",
            "description_en": "Timeless classic with bourbon whiskey, sugar cube, and aromatic bitters over a large ice block.",
            "ingredients": ["Bourbon Whisky", "Angostura Bitter", "Sugar Cube", "Orange Peel"],
            "badge": "Classic",
            "is_available": True
        },
        {
            "id": "c06",
            "name": "NEGRONI",
            "name_vi": "Negroni",
            "category": "cocktail",
            "station": "bar",
            "price": 190000,
            "description_vi": "Sự cân bằng hoàn hảo giữa Gin thượng hạng Tanqueray No.10, Sweet Vermouth và vị đắng đặc trưng Campari.",
            "description_en": "Perfect balance of Tanqueray No.10 Gin, Sweet Vermouth, and Campari with an orange twist.",
            "ingredients": ["Tanqueray No.10", "Sweet Vermouth", "Campari"],
            "badge": "Classic",
            "is_available": True
        },
        {
            "id": "c07",
            "name": "WHISKY SOUR",
            "name_vi": "Whisky Sour",
            "category": "cocktail",
            "station": "bar",
            "price": 190000,
            "description_vi": "Vị chua thanh mát mượt mà của whisky, chanh tươi và lớp bọt trứng trắng mịn màng.",
            "description_en": "Silky smooth balance of whiskey, freshly squeezed lemon juice, sugar, and egg white foam.",
            "ingredients": ["Whisky", "Fresh Lime/Lemon", "Egg White Foam", "Angostura"],
            "badge": "Classic",
            "is_available": True
        },
        {
            "id": "c08",
            "name": "MARGARITA",
            "name_vi": "Margarita",
            "category": "cocktail",
            "station": "bar",
            "price": 160000,
            "description_vi": "Tequila Jose Cuervo Gold hòa cùng rượu mùi cam Cointreau và chanh tươi, viền muối tinh thể.",
            "description_en": "Jose Cuervo Gold Tequila, Cointreau, fresh lime with a salted rim.",
            "ingredients": ["Jose Cuervo Gold Tequila", "Cointreau", "Lime", "Salt Rim"],
            "badge": "Classic",
            "is_available": True
        },
        {
            "id": "c09",
            "name": "GIN TONIC",
            "name_vi": "Gin Tonic",
            "category": "cocktail",
            "station": "bar",
            "price": 140000,
            "description_vi": "Sảng khoái thuần khiết với Gin cao cấp và Tonic sủi tăm mát lạnh kèm thảo mộc.",
            "description_en": "Clean and crisp Gin King Robert (or upgrade to Tanqueray No.10) with premium tonic water.",
            "ingredients": ["Gin", "Tonic Water", "Lime & Botanicals"],
            "badge": "Refreshing",
            "is_available": True
        },
        {
            "id": "c10",
            "name": "AMERICANO",
            "name_vi": "Americano",
            "category": "cocktail",
            "station": "bar",
            "price": 150000,
            "description_vi": "Món uống khai vị nhẹ nhàng sủi bọt, kết hợp Campari, Sweet Vermouth và soda.",
            "description_en": "Light aperitif pairing Campari and Sweet Vermouth topped with fizzy club soda.",
            "ingredients": ["Campari", "Sweet Vermouth", "Soda"],
            "badge": "Light & Bitter",
            "is_available": True
        },

        # --- MOCKTAILS (BAR) ---
        {
            "id": "m01",
            "name": "ROSY LYCHEE FIZZ / LỆ CHI TƯƠI",
            "name_vi": "Lệ Chi Tươi (Rosy Lychee)",
            "category": "mocktail",
            "station": "bar",
            "price": 110000,
            "description_vi": "Mùa hè trong ly: nhẹ, mát, đậm vị trái cây nhiệt đới với mận tự ngâm ủ, vị thanh ngọt dịu dàng mát lạnh bung xõa.",
            "description_en": "Summer in a glass — light, tropical, featuring house-fermented plum for subtle tang and depth. Zero alcohol.",
            "ingredients": ["Mứt mận nhà làm", "Trái vải tươi", "Soda sủi bọt", "Thảo mộc"],
            "badge": "No Alcohol / Best Seller",
            "is_available": True
        },
        {
            "id": "m02",
            "name": "COASTAL PLUM TEA",
            "name_vi": "Trà Mận Vùng Duyên Hải",
            "category": "mocktail",
            "station": "bar",
            "price": 90000,
            "description_vi": "Trà ô long, mứt mận nhà làm, nước mận lên men thủ công, syrup hạnh nhân. Phục vụ cùng viên kem mận gelato nhà làm.",
            "description_en": "Oolong tea, homemade plum puree, crafted plum syrup, orgeat syrup, acid water. Served with homemade plum gelato.",
            "ingredients": ["Trà Ô Long", "Mứt mận nhà làm", "Nước mận lên men", "Kem mận Gelato"],
            "badge": "Gelato Inside",
            "is_available": True
        },
        {
            "id": "m03",
            "name": "MANGO TANGO",
            "name_vi": "Mango Tango",
            "category": "mocktail",
            "station": "bar",
            "price": 90000,
            "description_vi": "Mứt xoài, chanh, trà đào, soda dứa lên men nhà làm. Phục vụ cùng lớp kem mặn béo vị dứa thơm ngậy.",
            "description_en": "Mango puree, lime juice, peach tea, homemade pineapple soda. Served with Salted Pineapple Cheese Foam.",
            "ingredients": ["Mứt xoài", "Trà đào", "Soda dứa lên men", "Salted Pineapple Cheese Foam"],
            "badge": "Cheese Foam",
            "is_available": True
        },
        {
            "id": "m04",
            "name": "PASSIONATE CRUNCH",
            "name_vi": "Passionate Crunch",
            "category": "mocktail",
            "station": "bar",
            "price": 90000,
            "description_vi": "Mứt cóc nhà làm, syrup chanh dây thủ công, hương lá dứa thanh mát và chanh tươi.",
            "description_en": "Ambarella puree, homemade passion fruit syrup, pandan syrup, fresh lime juice.",
            "ingredients": ["Mứt cóc nhà làm", "Syrup chanh dây", "Syrup lá dứa", "Chanh"],
            "badge": "Crisp & Sour",
            "is_available": True
        },
        {
            "id": "m05",
            "name": "CHERRY POP",
            "name_vi": "Cherry Pop",
            "category": "mocktail",
            "station": "bar",
            "price": 90000,
            "description_vi": "Mứt cherry đỏ mọng, trà ô long, chanh, syrup hạnh nhân. Phục vụ cùng lớp kem nhãn berry ngọt ngào.",
            "description_en": "Cherry puree, oolong tea, lime juice, orgeat syrup. Served with Logan Berry Foam.",
            "ingredients": ["Mứt cherry", "Trà ô long", "Syrup hạnh nhân", "Logan Berry Foam"],
            "badge": "Sweet Foam",
            "is_available": True
        },
        {
            "id": "m06",
            "name": "LYCHEE FIZZ",
            "name_vi": "Lychee Fizz",
            "category": "mocktail",
            "station": "bar",
            "price": 90000,
            "description_vi": "Mứt vải, mứt mận nhà làm, soda dứa lên men. Phục vụ cùng kem mận gelato hoặc lớp kem mặn béo.",
            "description_en": "Lychee puree, homemade plum puree, spice syrup, pineapple soda with plum gelato/cheese foam.",
            "ingredients": ["Mứt vải", "Mứt mận nhà làm", "Soda dứa", "Kem mận gelato"],
            "badge": "Sweet & Tangy",
            "is_available": True
        },

        # --- BEER, CIDER & TEPACHE (BAR) ---
        {
            "id": "br01",
            "name": "SUNNY PINT (HOPPY PILSNER ON TAP)",
            "name_vi": "Bia Thủ Công Sunny Pint (Rót Vòi)",
            "category": "beer",
            "station": "bar",
            "price": 65000,
            "description_vi": "Pilsner thiên về hoa bia thơm nức mũi, đậm mùi hoa bia hơn. AVB 5.2% - IBU 16.",
            "description_en": "Hoppy pilsner on tap, intensely aromatic hop character with crisp finish. AVB 5.2 - IBU 16.",
            "ingredients": ["Craft Beer on tap 330ml"],
            "badge": "On Tap / Craft",
            "is_available": True
        },
        {
            "id": "br02",
            "name": "CRISPY BOI (CLASSIC PILSNER ON TAP)",
            "name_vi": "Bia Thủ Công Crispy Boi (Rót Vòi)",
            "category": "beer",
            "station": "bar",
            "price": 65000,
            "description_vi": "Pilsner truyền thống, malt cân bằng mượt mà, giòn rụm cực kỳ dễ uống.",
            "description_en": "Classic traditional pilsner on tap, balanced malt body, ultra crisp drinkability.",
            "ingredients": ["Craft Beer on tap 330ml"],
            "badge": "On Tap / Craft",
            "is_available": True
        },
        {
            "id": "br03",
            "name": "KISO - TEPACHE DỨA LÊN MEN THỦ CÔNG",
            "name_vi": "Kiso - Tepache Dứa Lên Men",
            "category": "beer",
            "station": "bar",
            "price": 65000,
            "description_vi": "Đồ uống truyền thống từ Mexico ủ từ vỏ dứa chín, đường thốt nốt và quế. Vị chua thanh, sủi tăm tự nhiên, cực kỳ giải nhiệt. (330ml/ly).",
            "description_en": "Traditional Mexican fermented pineapple beverage crafted with ripe pineapple peel, piloncillo palm sugar, and cinnamon. Naturally effervescent.",
            "ingredients": ["Dứa tươi lên men thủ công", "Đường thốt nốt", "Quế thơm"],
            "badge": "Special Ferment",
            "is_available": True
        },
        {
            "id": "br04",
            "name": "HOEGAARDEN WITBIER",
            "name_vi": "Bia Bỉ Hoegaarden Trắng",
            "category": "beer",
            "station": "bar",
            "price": 65000,
            "description_vi": "Bia lúa mì trứ danh của Bỉ với hương vỏ cam cay nhẹ và hạt ngò rí thơm dịu. (250ml - AVB 4.9%).",
            "description_en": "Famous Belgian wheat beer with subtle notes of orange peel and coriander seed.",
            "ingredients": ["Chai 250ml"],
            "badge": "Wheat Beer",
            "is_available": True
        },
        {
            "id": "br05",
            "name": "CORONA EXTRA",
            "name_vi": "Bia Chai Corona Extra",
            "category": "beer",
            "station": "bar",
            "price": 85000,
            "description_vi": "Bia chai nhập khẩu Mexico kinh điển, phục vụ kèm lát chanh vàng tươi mát lạnh. (300ml - AVB 4.6%).",
            "description_en": "Classic Mexican lager served chilled with a fresh lime wedge.",
            "ingredients": ["Chai 300ml"],
            "badge": "Imported",
            "is_available": True
        },
        {
            "id": "br06",
            "name": "MICHELOB ULTRA LIGHT",
            "name_vi": "Bia Michelob Ultra Light",
            "category": "beer",
            "station": "bar",
            "price": 45000,
            "description_vi": "Bia nhẹ ít calo, êm dịu sảng khoái không lo nặng bụng. (250ml - AVB 4.2%).",
            "description_en": "Low-carb, light and refreshing American beer.",
            "ingredients": ["Lon 250ml"],
            "badge": "Low Carb",
            "is_available": True
        },
        {
            "id": "br07",
            "name": "CRAFT CIDER (APPLE / BLACKBERRY)",
            "name_vi": "Cider Táo / Mâm Xôi Đen",
            "category": "beer",
            "station": "bar",
            "price": 75000,
            "description_vi": "Nước táo và dâu mâm xôi đen lên men tự nhiên, chua ngọt sủi bọt thơm lừng mát rượi.",
            "description_en": "Naturally fermented sparkling apple & blackberry craft cider.",
            "ingredients": ["Ly 330ml"],
            "badge": "Fruity",
            "is_available": True
        },

        # --- WINE & SHOTS (BAR) ---
        {
            "id": "wn01",
            "name": "CHATEAU DALAT TRADITION MERLOT",
            "name_vi": "Vang Đỏ Chateau Dalat Merlot",
            "category": "wine_shot",
            "station": "bar",
            "price": 85000,
            "description_vi": "Vang đỏ đượm đà vị nho Merlot lên men gỗ sồi, nồng nàn quyến rũ giữa cái se lạnh Đà Lạt. (150ml/Ly).",
            "description_en": "Oak-aged Dalat red wine made from Merlot grapes, smooth and rich (150ml glass).",
            "ingredients": ["Ly 150ml"],
            "badge": "By The Glass",
            "is_available": True
        },
        {
            "id": "sh01",
            "name": "SHOT TANQUERAY NO.10 GIN",
            "name_vi": "Shot Rượu Tanqueray No.10 Gin",
            "category": "wine_shot",
            "station": "bar",
            "price": 120000,
            "description_vi": "Shot Gin thảo mộc cam chanh tươi cao cấp nhất của Tanqueray (40ml).",
            "description_en": "Premium small-batch London Dry Gin shot (40ml).",
            "ingredients": ["Shot 40ml"],
            "badge": "Shot 40ml",
            "is_available": True
        },
        {
            "id": "sh02",
            "name": "SHOT BLACK LABEL BLENDED WHISKY",
            "name_vi": "Shot Rượu Black Label Whisky",
            "category": "wine_shot",
            "station": "bar",
            "price": 120000,
            "description_vi": "Hương vị khói than bùn đặc trưng và gỗ sồi 12 năm tuổi của Johnnie Walker (40ml).",
            "description_en": "Iconic 12-year-old blended Scotch whisky with rich smoke and oak notes (40ml).",
            "ingredients": ["Shot 40ml"],
            "badge": "Shot 40ml",
            "is_available": True
        },
        {
            "id": "sh03",
            "name": "SHOT JOSE CUERVO GOLD TEQUILA",
            "name_vi": "Shot Rượu Jose Cuervo Gold",
            "category": "wine_shot",
            "station": "bar",
            "price": 100000,
            "description_vi": "Tequila vàng cay nồng kèm chanh và muối khai tiệc (40ml).",
            "description_en": "Classic Mexican gold tequila served with lime & salt (40ml).",
            "ingredients": ["Shot 40ml"],
            "badge": "Shot 40ml",
            "is_available": True
        }
    ]
}

with open(r'D:\paca\data\menu.json', 'w', encoding='utf-8') as f:
    json.dump(menu_data, f, ensure_ascii=False, indent=2)

print("Created D:\paca\data\menu.json with", len(menu_data["items"]), "items across", len(menu_data["categories"]), "categories.")
